import assert from 'node:assert/strict';
import { contextPayload, replaceContext, contextKey } from '../frontend-vue/src/lib/ml.js';
import { eventPayload, decisionKey } from '../frontend-vue/src/lib/api.js';
const fields=[{key:'temp',kind:'number'},{key:'equipment',kind:'category'}];
const payload=contextPayload('cause',fields,{temp:'0',equipment:'cold-box'},'S1');
assert.deepEqual(payload.features,{temp:0,equipment:'cold-box'});
assert.equal(payload.source,'dataset_sample');
assert.throws(()=>contextPayload('risk',fields,{temp:'',equipment:'x'}));
assert.throws(()=>contextPayload('risk',fields,{temp:'NaN',equipment:'x'}));
const list=replaceContext([{task:'risk',features:{}}],'cause',payload);
assert.equal(list.length,2); payload.features.temp=10;
assert.equal(list[1].features.temp,0);
assert.equal(replaceContext(list,'cause').length,1);
const ev={product_id:'vaccine_2_8',excursion_temp_c:5,duration_min:0,mkt_c:5,packaging:'intact',stage:'transit'};
const spec={allowable:30,mktThreshold:10,retestable:true};
assert.equal(eventPayload(ev).ml_contexts,undefined);
const attached={...ev,ml_contexts:list};
assert.notEqual(decisionKey(ev,spec),decisionKey(attached,spec));
assert.deepEqual(eventPayload(attached).ml_contexts,list);
assert.notEqual(contextKey(payload),contextKey(list[1]));
console.log('M4 payload, zero values, model/heuristic separation and immutable context selection passed.');
